name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --output-path docs --base-href /boutique-shop/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs  # This should match the output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
